### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [hanjunlee/terragrunt-oh-my-zsh-plugin#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by noahingh** [comment]
@unixorn I have added the license. Thank you for your recommendation!

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/710
